=== GeeXboX/mplayer-ui/TOOLS/mpui.dtd
<!ELEMENT mpui (include | strings | images | fonts | objects | menus
              | screens)*>

<!ELEMENT include EMPTY>
<!ELEMENT strings (string)*>
<!ELEMENT images (image)*>
<!ELEMENT fonts (font)*>
<!ELEMENT objects (object)*>
<!ELEMENT menus (menu)*>
<!ELEMENT screens (screen)*>

<!ELEMENT menu (obj | str | img | all-menu-items | menu-item)*>
<!ELEMENT screen (obj | str | img | mnu)*>

<!ELEMENT string EMPTY>
<!ELEMENT image EMPTY>
<!ELEMENT str EMPTY>
<!ELEMENT img EMPTY>
<!ELEMENT obj EMPTY>
<!ELEMENT mnu EMPTY>
<!ELEMENT font EMPTY>
<!ELEMENT object (obj | str | img | action)*>
<!ELEMENT all-menu-items (obj | str | img | action)*>
<!ELEMENT menu-item (obj | str | img | action)*>
<!ELEMENT action EMPTY>

<!ATTLIST include file CDATA #REQUIRED>
<!ATTLIST strings encoding NMTOKEN #IMPLIED
                  lang NMTOKEN #IMPLIED>
<!ATTLIST fonts default NMTOKEN #REQUIRED>
<!ATTLIST menu id NMTOKEN #REQUIRED
               orientation NMTOKEN "vertical"
               font NMTOKEN #REQUIRED
               x CDATA #REQUIRED
               y CDATA #REQUIRED
               h CDATA #REQUIRED
               w CDATA #REQUIRED>
<!ATTLIST mnu id NMTOKEN #REQUIRED
              font NMTOKEN #IMPLIED
              x CDATA #IMPLIED
              y CDATA #IMPLIED
              h CDATA #IMPLIED
              w CDATA #IMPLIED>
<!ATTLIST screens menu NMTOKEN #IMPLIED
                  control NMTOKEN #IMPLIED>
<!ATTLIST screen id NMTOKEN #REQUIRED>

<!ATTLIST string id NMTOKEN #REQUIRED
                 text CDATA #REQUIRED>
<!ATTLIST str id NMTOKEN #REQUIRED
              x CDATA #IMPLIED
              y CDATA #IMPLIED
              font NMTOKEN #IMPLIED
              size CDATA #IMPLIED
              color CDATA #IMPLIED
              focused-color CDATA #IMPLIED
              when-focused NMTOKEN #IMPLIED>

<!ATTLIST image id NMTOKEN #REQUIRED
                file CDATA #REQUIRED
                x CDATA #IMPLIED
                y CDATA #IMPLIED
                h CDATA #IMPLIED
                w CDATA #IMPLIED>
<!ATTLIST img id NMTOKEN #REQUIRED
              x CDATA #IMPLIED
              y CDATA #IMPLIED
              h CDATA #IMPLIED
              w CDATA #IMPLIED
              when-focused NMTOKEN #IMPLIED>

<!ATTLIST font id NMTOKEN #REQUIRED
               file CDATA #REQUIRED
               size CDATA "12"
               color CDATA "#000000"
               focused-color CDATA "#000000">

<!ATTLIST object id NMTOKEN #REQUIRED
                 relative NMTOKEN "no"
                 dynamic NMTOKEN "no">      
<!ATTLIST obj id NMTOKEN #REQUIRED
              when-focused NMTOKEN #IMPLIED>

<!ATTLIST action cmd CDATA #REQUIRED>

=== GeeXboX/mplayer-ui/etc/mpui_fr.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mpui SYSTEM "mpui.dtd">

<mpui>
  <strings fonts="iso-8859-1" lang="fr">
    <string id="version" text="Version de Développement pre0.99\nGeeXboX Team (C) 2005"/>
    <string id="media_menu" text="Lecteur Multimédia"/>
    <string id="play_menu" text="Lire un CD/DVD"/>
    <string id="tv_menu" text="Regarder la TV"/>
    <string id="playlist_menu" text="Editeur de Playlist"/>    
    <string id="settings_menu" text="Configuration"/>

    <string id="media_screen_title" text="Lecteur Multimédia"/>
    <string id="media_all_files" text="Tous fichiers"/>
    <string id="media_movie_files" text="Fichiers vidéo seulement"/>
    <string id="media_music_files" text="Fichiers audio seulement"/>
    <string id="media_picture_files" text="Images seulement"/>
    <string id="media_playlist_files" text="Playlists"/>

    <string id="tv_screen_title" text="Centre TV"/>
    <string id="tv_analog" text="TV analogique"/>
    <string id="tv_digital" text="TV numérique"/>
    <string id="tv_analog_channel" text="Chaines hertziennes"/>
    <string id="tv_digital_channel" text="Chaines numériques"/>
    <string id="tv_video_in" text="Entrée Vidéo"/>

    <string id="playlist_screen_title" text="Editeur de Playlist"/>
    <string id="settings_screen_title" text="Configuration"/>

    <string id="txt_help" file="help_en.txt"/>
    <string id="txt_info" text="Informations Systèmes"/>
  </strings>
</mpui>

=== GeeXboX/mplayer-ui/etc/mpui-theme.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE mpui SYSTEM "mpui.dtd">

<mpui>
  <strings encoding="iso8859-1">
    <string id="watch_tv" text="Watch TV"/>
    <string id="play_dvd" text="Play DVD"/>
    <string id="view_img" text="View Pictures"/>
    <string id="play_mov" text="Play Movies"/>
    <string id="play_snd" text="Jukebox"/>
    <string id="settings" text="Settings TV"/>
  </strings>

  <images>
    <image id="back" file="background.png" x="0" y="0" h="100%" w="100%"/>
    <image id="logo_gx" file="logo_gx.png" x="70%" y="0%" h="13%" w="30%"/>

    <image id="help" file="help.png" x="80%" y="90%" h="10%" w="8%"/>
    <image id="help_focus" file="help_focus.png" x="85%" y="90%" h="10%" w="8%"/>
    <image id="quit" file="quit.png" x="89%" y="90%" h="10%" w="8%"/>
    <image id="quit_focus" file="quit_focus.png" x="89%" y="90%" h="10%" w="8%"/>

    <image id="sep" file="separator.png"/>

    <image id="logo_tv" file="logo_tv.png" x="5%" y="30%" h="30%" w="30%"/>
    <image id="logo_dvd" file="logo_dvd.png" x="5%" y="30%" h="30%" w="30%"/>
    <image id="logo_img" file="logo_img.png" x="5%" y="30%" h="30%" w="30%"/>
    <image id="logo_mov" file="logo_mov.png" x="5%" y="30%" h="30%" w="30%"/>
    <image id="logo_snd" file="logo_snd.png" x="5%" y="30%" h="30%" w="30%"/>
    <image id="logo_set" file="logo_set.png" x="5%" y="30%" h="30%" w="30%"/>
  </images>

  <fonts default="menu_font">
    <font id="menu_font" file="Handycandy.ttf" size="12"
                         color="#ffffff" focused-color="#ffff81"/>
  </fonts>

  <objects>
    <object id="menu-item-border" relative="yes">
      <img id="border-horiz" x="left" y="top-5%" w="width" h="2%"/>
      <img id="border-horiz" x="left" y="bottom+5%" w="width" h="2%"/>
      <img id="border-vert" x="left-5%" y="top" w="2%" h="height"/>
      <img id="border-vert" x="right+5%" y="top" w="2%" h="height"/>
      <img id="border-top-left" x="left-5%" y="top-5%" w="2%" h="2%"/>
      <img id="border-top-right" x="right+5%" y="top-5%" w="2%" h="2%"/>
      <img id="border-bottom-right" x="right+5%" y="bottom+5%" w="2%" h="2%"/>
      <img id="border-bottom-left" x="left-5%" y="bottom+5%" w="2%" h="2%"/>
    </object>
    <object id="menu-border" relative="yes">
      <img id="menu-border-horiz" x="left" y="top-5%" w="width" h="2%"/>
      <img id="menu-border-horiz" x="left" y="bottom+5%" w="width" h="2%"/>
      <img id="menu-border-vert" x="left-5%" y="top" w="2%" h="height"/>
      <img id="menu-border-vert" x="right+5%" y="top" w="2%" h="height"/>
      <img id="menu-border-top-left" x="left-5%" y="top-5%" w="2%" h="2%"/>
      <img id="menu-border-top-right" x="right+5%" y="top-5%" w="2%" h="2%"/>
      <img id="menu-border-bottom-right" x="right+5%" y="bottom+5%" w="2%" h="2%"/>
      <img id="menu-border-bottom-left" x="left-5%" y="bottom+5%" w="2%" h="2%"/>
    </object>
    <object id="help_button" dynamic="yes">
      <img id="help" when-focused="no"/>
      <img id="help_focus" when-focused="yes"/>
      <action cmd="screen help_screen"/>
    </object>
    <object id="quit_button" dynamic="yes">
      <img id="quit" when-focused="no"/>
      <img id="quit_focus" when-focused="yes"/>
      <action cmd="exit"/>
    </object>
  </objects>

  <menus>
    <menu id="main-menu" orientation="vertical" font="menu_font"
                         x="50%" y="20%" h="60%" w="40%">

      <obj id="menu-border"/>

      <all-menu-items>
        <obj id="menu-item-border" when-focused="yes"/>
      </all-menu-items>

      <menu-item>
        <str id="watch_tv"/>
        <action cmd="screen tv_screen"/>
        <img id="logo_tv" when-focused="yes"/>
      </menu-item>

      <menu-item>
        <str id="play_dvd"/>
        <action cmd="play dvd://"/>
        <img id="logo_dvd" when-focused="yes"/>
      </menu-item>

      <menu-item>
        <str id="view_img"/>
        <action cmd="screen img_screen"/>
        <img id="logo_img" when-focused="yes"/>
      </menu-item>

      <menu-item>
        <str id="play_mov"/>
        <action cmd="screen video_screen"/>
        <img id="logo_mov" when-focused="yes"/>
      </menu-item>

      <menu-item>
        <str id="play_snd"/>
        <action cmd="screen audio_screen"/>
        <img id="logo_snd" when-focused="yes"/>
      </menu-item>

      <img id="separator"/>

      <menu-item>
        <str id="settings"/>
        <action cmd="screen settings_screen"/>
        <img id="logo_set" when-focused="yes"/>
      </menu-item>
    </menu>
  </menus>

  <screens menu="main_screen" control="ctrl_screen">
    <screen id="main_screen">
      <img id="back"/>
      <img id="logo_gx"/>
      <obj id="help_button"/>
      <obj id="quit_button"/>
      <mnu id="main-menu"/>
    </screen>
  </screens>
</mpui>

=== GeeXboX/mplayer-ui/etc/mpui_zh.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE mpui SYSTEM "mpui.dtd">

<mpui>
  <strings fonts="gb2312" lang="zh">
    <string id="version" text="Devel"/>
    <string id="media_menu" text="打开文件"/>
    <string id="play_menu" text="打开文件夹"/>
    <string id="tv_menu" text="播放音乐CD"/>
    <string id="playlist_menu" text="选择章节/曲目"/>    
    <string id="settings_menu" text="Settings"/>

    <string id="media_screen_title" text="Media Browser"/>
    <string id="media_all_files" text="All files"/>
    <string id="media_movie_files" text="Movie files"/>
    <string id="media_music_files" text="Music files"/>
    <string id="media_picture_files" text="Picture files"/>
    <string id="media_playlist_files" text="Playlists"/>

    <string id="tv_screen_title" text="TV Center"/>
    <string id="tv_analog" text="Analog TV"/>
    <string id="tv_digital" text="Digital TV"/>
    <string id="tv_analog_channel" text="Analog Channels"/>
    <string id="tv_digital_channel" text="Digital Channels"/>
    <string id="tv_video_in" text="Video In"/>

    <string id="playlist_screen_title" text="Playlist Editor"/>
    <string id="settings_screen_title" text="Settings"/>

    <string id="txt_help" file="help_en.txt"/>
    <string id="txt_info" text="System's Information"/>
  </strings>
</mpui>

=== GeeXboX/mplayer-ui/etc/mpui_en.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE mpui SYSTEM "mpui.dtd">

<mpui>
  <strings encoding="iso8859-1">
    <string id="version" text="Development Release pre0.99\nGeeXboX Team (C) 2004"/>
    <string id="watch_tv" text="Watch TV"/>
    <string id="tv" text="TV Center"/>
    <string id="play_dvd" text="Play CD/DVD"/>
    <string id="view_img" text="Pictures Viewer"/>
    <string id="img" text="Pictures Viewer"/>
    <string id="play_mov" text="Play Movies"/>
    <string id="mov" text="Movie Player"/>
    <string id="play_snd" text="Jukebox"/>
    <string id="snd" text="Audio Jukebox"/>
    <string id="settings" text="Settings"/>
    <string id="txt_help" file="help_en.txt"/>
    <string id="txt_info" text="System's Information"/>
  </strings>
</mpui>
